// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgcMBaEiFEWvBOJ_LMXnwPv_wCzdezcU',
    appId: '1:867410211046:web:4be45752c55b5d16bc4b27',
    messagingSenderId: '867410211046',
    projectId: 'mtra-e89e1',
    authDomain: 'mtra-e89e1.firebaseapp.com',
    storageBucket: 'mtra-e89e1.firebasestorage.app',
    measurementId: 'G-QPL8K35DWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5E40NVbNuSeWHvZqjyaEyF-CnrAHD4F0',
    appId: '1:867410211046:android:795f3e6b3f1f127ebc4b27',
    messagingSenderId: '867410211046',
    projectId: 'mtra-e89e1',
    storageBucket: 'mtra-e89e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU9ZKAlL1ZdV-OIiTBIoMwc7MJ8JfUSWY',
    appId: '1:867410211046:ios:19fb9d6ce56ef54cbc4b27',
    messagingSenderId: '867410211046',
    projectId: 'mtra-e89e1',
    storageBucket: 'mtra-e89e1.firebasestorage.app',
    iosBundleId: 'com.example.mtra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU9ZKAlL1ZdV-OIiTBIoMwc7MJ8JfUSWY',
    appId: '1:867410211046:ios:19fb9d6ce56ef54cbc4b27',
    messagingSenderId: '867410211046',
    projectId: 'mtra-e89e1',
    storageBucket: 'mtra-e89e1.firebasestorage.app',
    iosBundleId: 'com.example.mtra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLgcMBaEiFEWvBOJ_LMXnwPv_wCzdezcU',
    appId: '1:867410211046:web:a2ba684194f21126bc4b27',
    messagingSenderId: '867410211046',
    projectId: 'mtra-e89e1',
    authDomain: 'mtra-e89e1.firebaseapp.com',
    storageBucket: 'mtra-e89e1.firebasestorage.app',
    measurementId: 'G-7ZKR8B7LWY',
  );
}
